<a href="https://colab.research.google.com/github/mralamdari/Python-Projects/blob/main/Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

#Binary numbers

##Integer to Binary

In [8]:
def int2bin(number, bit_size):
  binary_list = []
  while bit_size>0:
    bit_size -= 1
    binary_list.append(number % 2)
    number //= 2
  binary_list.reverse()
  return binary_list

In [9]:
def bin2int(bits):
  bits.reverse()
  decimal, counter = 0, 0
  for i in bits:
    decimal += 2**counter * int(i)
    counter += 1
  return decimal

In [10]:
def seq2str(binary_list):
  binary_str = ''
  for i in binary_list:
    binary_str += f'{i}'
  return binary_str

In [11]:
# number = int(input('Enter a number:'))
number = 250
bit_size = 15

binary_list = int2bin(number, bit_size)
binary_str = seq2str(binary_list)
decimal_list = bin2int(binary_list)
print(f'Binary List is: {binary_list}')
print(f'Binary Number is: {binary_str}')
print(f'Decimal Number is: {decimal_list}')

Binary List is: [0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
Binary Number is: 000000011111010
Decimal Number is: 250


##Mutation

In [12]:
def mutation(seq, m_rate=0.3):
  new_seq = []
  for item in seq:
    if np.random.randn() < m_rate:
      item = 0 if item==1 else 0
    new_seq.append(item)
  return new_seq

In [13]:
mutation(binary_list)

[0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

##Crossover

In [14]:
seq1 = mutation(binary_list)
seq2 = mutation(binary_list)

print(seq2str(seq1))
print(seq2str(seq2))
print('\n')
print(seq2str(seq1[:5] + seq2[5+1:]))
print(seq2str(seq2[:5] + seq1[5+1:]))

np.random.randint(0, 10, 3)

010000000000000
010100010000000


01000010000000
01010000000000


array([0, 6, 4])

In [15]:
num = 2
p = np.random.rand(len(seq1))
# print(p)
p
# rand_ind = np.random.choice(seq1, replace=False, p=p)

array([0.61934495, 0.01052207, 0.16909182, 0.68171724, 0.36887568,
       0.73410875, 0.14435753, 0.70959518, 0.23851441, 0.69327801,
       0.63497716, 0.73461761, 0.0238339 , 0.01419508, 0.35797814])

In [16]:
def uniform_crossover(seq1, seq2, rate=0.2):
  new_seq1, new_seq2 = [], []
  for id, rand in enumerate(np.random.rand(len(seq1))):
    if rand < rate:
      new_seq1.append(seq1[id])
      new_seq2.append(seq2[id])
    else:
      new_seq1.append(seq2[id])
      new_seq2.append(seq1[id])

  return new_seq1, new_seq2

In [17]:
seq1 = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
seq2 = [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0]

new_seq1, new_seq2 = uniform_crossover(seq1, seq2, 0.5)

print(seq2str(seq1))
print(seq2str(seq2))
print('\n')
print(seq2str(new_seq1))
print(seq2str(new_seq2))

000001000000000
010100101010000


010101000010000
000000101000000


#Real Numbers

uniform_mutation

In [23]:
# def uniform_mutation(seq):
#   return np.random.randn()
min, max, num = 1, 100, 200
np.random.randint(min, max, num) / 100

array([0.18, 0.34, 0.69, 0.79, 0.44, 0.54, 0.02, 0.7 , 0.12, 0.55, 0.4 ,
       0.1 , 0.66, 0.27, 0.45, 0.64, 0.83, 0.23, 0.67, 0.23, 0.72, 0.57,
       0.23, 0.45, 0.4 , 0.58, 0.61, 0.61, 0.76, 0.09, 0.35, 0.12, 0.85,
       0.9 , 0.57, 0.71, 0.04, 0.28, 0.11, 0.31, 0.21, 0.78, 0.57, 0.86,
       0.27, 0.7 , 0.77, 0.16, 0.07, 0.08, 0.62, 0.2 , 0.32, 0.14, 0.14,
       0.95, 0.91, 0.44, 0.98, 0.82, 0.22, 0.54, 0.11, 0.68, 0.27, 0.05,
       0.41, 0.41, 0.27, 0.42, 0.13, 0.91, 0.71, 0.76, 0.98, 0.32, 0.02,
       0.39, 0.94, 0.15, 0.91, 0.51, 0.16, 0.7 , 0.94, 0.37, 0.09, 0.43,
       0.59, 0.31, 0.43, 0.72, 0.58, 0.3 , 0.89, 0.13, 0.5 , 0.82, 0.92,
       0.08, 0.37, 0.29, 0.13, 0.94, 0.03, 0.22, 0.17, 0.35, 0.56, 0.78,
       0.94, 0.77, 0.87, 0.6 , 0.77, 0.68, 0.26, 0.17, 0.89, 0.75, 0.41,
       0.72, 0.07, 0.21, 0.18, 0.42, 0.48, 0.74, 0.65, 0.07, 0.39, 0.45,
       0.67, 0.8 , 0.83, 0.07, 0.63, 0.53, 0.37, 0.63, 0.84, 0.38, 0.1 ,
       0.91, 0.97, 0.2 , 0.87, 0.92, 0.06, 0.87, 0.

In [ ]:
numpy.random.uniform