<a href="https://colab.research.google.com/github/mralamdari/Python-Projects/blob/main/Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Binary numbers

##Integer to Binary

In [ ]:
def int2bin(number, bit_size):
  binary_list = []
  while bit_size>0:
    bit_size -= 1
    binary_list.append(number % 2)
    number //= 2
  binary_list.reverse()
  return binary_list

In [ ]:
def bin2int(bits):
  bits.reverse()
  decimal, counter = 0, 0
  for i in bits:
    decimal += 2**counter * int(i)
    counter += 1
  return decimal

In [ ]:
def seq2str(binary_list):
  binary_str = ''
  for i in binary_list:
    binary_str += f'{i}'
  return binary_str

In [ ]:
# number = int(input('Enter a number:'))
number = 250
bit_size = 15

binary_list = int2bin(number, bit_size)
binary_str = seq2str(binary_list)
decimal_list = bin2int(binary_list)
print(f'Binary List is: {binary_list}')
print(f'Binary Number is: {binary_str}')
print(f'Decimal Number is: {decimal_list}')

Binary List is: [0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
Binary Number is: 000000011111010
Decimal Number is: 250


##Mutation

In [ ]:
def mutation(seq, m_rate=0.3):
  new_seq = []
  for item in seq:
    if np.random.randn() < m_rate:
      item = 0 if item==1 else 0
    new_seq.append(item)
  return new_seq

In [ ]:
mutation(binary_list)

[0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

##Crossover

In [ ]:
seq1 = mutation(binary_list)
seq2 = mutation(binary_list)

print(seq2str(seq1))
print(seq2str(seq2))
print('\n')
print(seq2str(seq1[:5] + seq2[5+1:]))
print(seq2str(seq2[:5] + seq1[5+1:]))

np.random.randint(0, 10, 3)

010111110000000
000000100000000


01011100000000
00000110000000


array([0, 6, 9])

In [ ]:
def uniform_crossover(seq1, seq2, rate=0.2):
  new_seq1, new_seq2 = [], []
  for id, rand in enumerate(np.random.rand(len(seq1))):
    if rand < rate:
      new_seq1.append(seq1[id])
      new_seq2.append(seq2[id])
    else:
      new_seq1.append(seq2[id])
      new_seq2.append(seq1[id])

  return new_seq1, new_seq2

In [ ]:
seq1 = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
seq2 = [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0]

new_seq1, new_seq2 = uniform_crossover(seq1, seq2, 0.5)

print(seq2str(seq1))
print(seq2str(seq2))
print('\n')
print(seq2str(new_seq1))
print(seq2str(new_seq2))

000001000000000
010100101010000


000100101010000
010001000000000


#Real Numbers

uniform_mutation

In [2]:
min, max, num = -1, 1, 50
# uniform_mutation = lambda min, max, num : np.random.randint(min*10, max*10, num)/10
uniform_mutation = lambda min, max, num : np.round(np.random.uniform(min, max, num), 3)

uniform_mutation(min, max, num)

array([ 0.025,  0.896, -0.56 , -0.581, -0.084,  0.414,  0.698,  0.873,
        0.871, -0.146,  0.657,  0.528,  0.919,  0.29 , -0.037,  0.363,
       -0.431,  0.938, -0.807,  0.894, -0.418, -0.328,  0.656, -0.36 ,
       -0.577, -0.247, -0.004, -0.378, -0.208, -0.523,  0.793, -0.537,
        0.211,  0.245, -0.2  ,  0.098, -0.476,  0.62 , -0.938,  0.49 ,
       -0.854,  0.588,  0.241, -0.48 ,  0.471,  0.751, -0.712, -0.46 ,
       -0.1  ,  0.39 ])

non-uniform_mutation

In [3]:
mu, sigma = 0, 0.1 # mean and standard deviation
non_uniform_mutation = lambda mu, sigma, num : np.round(np.random.normal(mu, sigma, num), 3)

non_uniform_mutation(mu, sigma, num)

array([ 0.033, -0.12 ,  0.119,  0.171,  0.032,  0.007,  0.065,  0.046,
        0.094,  0.135,  0.083, -0.027,  0.054, -0.009,  0.095, -0.038,
        0.039, -0.123,  0.024, -0.051,  0.022,  0.084, -0.044, -0.087,
       -0.178, -0.186, -0.113,  0.203,  0.041,  0.006, -0.149,  0.238,
        0.079, -0.117, -0.088,  0.   ,  0.034, -0.101, -0.199,  0.052,
       -0.011,  0.159, -0.061, -0.087,  0.105,  0.072,  0.127,  0.082,
        0.051, -0.077])

Arithmetic Recombination

In [4]:
def arithmetic_recombination(seq1, seq2, k=0, alpha=0.5):
  new_seq1, new_seq2 = seq1.copy(), seq2.copy()
  for id, s1, s2 in zip(range(len(seq1[k:])), seq1[k:], seq2[k:]):
    new_seq1[id+k] = alpha * s1 + (1 - alpha) * s2
    new_seq2[id+k] = alpha * s2 + (1 - alpha) * s1

  return np.round(new_seq1, 3), np.round(new_seq2, 3)

In [5]:
num = 20
seq1 = uniform_mutation(min, max, num)
seq2 = uniform_mutation(min, max, num)

new_seq1, new_seq2 = arithmetic_recombination(seq1, seq2, k=5, alpha=0.3)

print(seq1)
print(seq2)
print('\n')
print(new_seq1)
print(new_seq2)

[ 0.956  0.629 -0.44   0.401  0.3   -0.806 -0.79  -0.142 -0.726  0.208
  0.705 -0.013 -0.013  0.213  0.331  0.204  0.839 -0.751  0.677 -0.605]
[-0.616 -0.011 -0.967  0.154 -0.774  0.636  0.495  0.999 -0.811 -0.711
  0.498 -0.18   0.388  0.835 -0.692  0.8   -0.611 -0.493 -0.315  0.817]


[ 0.956  0.629 -0.44   0.401  0.3    0.203  0.109  0.657 -0.786 -0.435
  0.56  -0.13   0.268  0.648 -0.385  0.621 -0.176 -0.57  -0.017  0.39 ]
[-0.616 -0.011 -0.967  0.154 -0.774 -0.373 -0.404  0.2   -0.752 -0.068
  0.643 -0.063  0.107  0.4    0.024  0.383  0.404 -0.674  0.379 -0.178]
