<a href="https://colab.research.google.com/github/mralamdari/Python-Projects/blob/main/Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

#Binary numbers

##Integer to Binary

In [23]:
def int2bin(number, bit_size):
  binary_list = []
  while bit_size>0:
    bit_size -= 1
    binary_list.append(number % 2)
    number //= 2
  binary_list.reverse()
  return binary_list

In [31]:
def bin2int(bits):
  bits.reverse()
  decimal, counter = 0, 0
  for i in bits:
    decimal += 2**counter * int(i)
    counter += 1
  return decimal

In [32]:
def seq2str(binary_list):
  binary_str = ''
  for i in binary_list:
    binary_str += f'{i}'
  return binary_str

In [36]:
# number = int(input('Enter a number:'))
number = 250
bit_size = 15

binary_list = int2bin(number, bit_size)
binary_str = seq2str(binary_list)
decimal_list = bin2int(binary_list)
print(f'Binary List is: {binary_list}')
print(f'Binary Number is: {binary_str}')
print(f'Decimal Number is: {decimal_list}')

Binary List is: [0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
Binary Number is: 000000011111010
Decimal Number is: 250


##Mutation

In [21]:
def mutation(seq, m_rate=0.3):
  new_seq = []
  for item in seq:
    if np.random.randn() < m_rate:
      item = 0 if item==1 else 0
    new_seq.append(item)
  return new_seq

In [66]:
mutation(binary_list)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]

##Crossover

In [49]:
seq1 = mutation(binary_list)
seq2 = mutation(binary_list)

print(seq2str(seq1))
print(seq2str(seq2))
print('\n')
print(seq2str(seq1[:5] + seq2[5+1:]))
print(seq2str(seq2[:5] + seq1[5+1:]))

np.random.randint(0, 10, 3)

010001000000000
000111100000000


01000100000000
00011000000000


array([7, 0, 0])

In [108]:
num = 2
p = np.random.rand(len(seq1))
# print(p)
p
# rand_ind = np.random.choice(seq1, replace=False, p=p)

array([0.05737352, 0.58139386, 0.55918877, 0.16270399, 0.00640151,
       0.92258685, 0.25367614, 0.41057418, 0.54831335, 0.06128373,
       0.29733657, 0.38072504, 0.49563232, 0.23372005, 0.71307172])

In [114]:
def uniform_crossover(seq1, seq2, rate=0.2):
  new_seq1, new_seq2 = [], []
  for id, rand in enumerate(np.random.rand(len(seq1))):
    if rand < rate:
      new_seq1.append(seq1[id])
      new_seq2.append(seq2[id])
    else:
      new_seq1.append(seq2[id])
      new_seq2.append(seq1[id])

  return new_seq1, new_seq2

In [116]:
seq1 = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
seq2 = [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0]

new_seq1, new_seq2 = uniform_crossover(seq1, seq2, 0.5)

print(seq2str(seq1))
print(seq2str(seq2))
print('\n')
print(seq2str(new_seq1))
print(seq2str(new_seq2))

000001000000000
010100101010000


000100100010000
010001001000000


#Real Numbers

uniform_mutation

In [119]:
# def uniform_mutation(seq):
#   return np.random.randn()

np.random.rand(4)

array([0.23002775, 0.60077482, 0.79621741, 0.81557445])