<a href="https://colab.research.google.com/github/mralamdari/Python-Projects/blob/main/Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#Binary numbers

##Integer to Binary

In [ ]:
def int2bin(number, bit_size):
  binary_list = []
  while bit_size>0:
    bit_size -= 1
    binary_list.append(number % 2)
    number //= 2
  binary_list.reverse()
  return binary_list

In [ ]:
def bin2int(bits):
  bits.reverse()
  decimal, counter = 0, 0
  for i in bits:
    decimal += 2**counter * int(i)
    counter += 1
  return decimal

In [ ]:
def seq2str(binary_list):
  binary_str = ''
  for i in binary_list:
    binary_str += f'{i}'
  return binary_str

In [ ]:
# number = int(input('Enter a number:'))
number = 250
bit_size = 15

binary_list = int2bin(number, bit_size)
binary_str = seq2str(binary_list)
decimal_list = bin2int(binary_list)
print(f'Binary List is: {binary_list}')
print(f'Binary Number is: {binary_str}')
print(f'Decimal Number is: {decimal_list}')

Binary List is: [0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
Binary Number is: 000000011111010
Decimal Number is: 250


##Mutation

In [ ]:
def mutation(seq, m_rate=0.3):
  new_seq = []
  for item in seq:
    if np.random.randn() < m_rate:
      item = 0 if item==1 else 0
    new_seq.append(item)
  return new_seq

In [ ]:
mutation(binary_list)

[0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

##Crossover

In [ ]:
seq1 = mutation(binary_list)
seq2 = mutation(binary_list)

print(seq2str(seq1))
print(seq2str(seq2))
print('\n')
print(seq2str(seq1[:5] + seq2[5+1:]))
print(seq2str(seq2[:5] + seq1[5+1:]))

np.random.randint(0, 10, 3)

010000000000000
010100010000000


01000010000000
01010000000000


array([0, 6, 4])

In [ ]:
num = 2
p = np.random.rand(len(seq1))
# print(p)
p
# rand_ind = np.random.choice(seq1, replace=False, p=p)

array([0.61934495, 0.01052207, 0.16909182, 0.68171724, 0.36887568,
       0.73410875, 0.14435753, 0.70959518, 0.23851441, 0.69327801,
       0.63497716, 0.73461761, 0.0238339 , 0.01419508, 0.35797814])

In [ ]:
def uniform_crossover(seq1, seq2, rate=0.2):
  new_seq1, new_seq2 = [], []
  for id, rand in enumerate(np.random.rand(len(seq1))):
    if rand < rate:
      new_seq1.append(seq1[id])
      new_seq2.append(seq2[id])
    else:
      new_seq1.append(seq2[id])
      new_seq2.append(seq1[id])

  return new_seq1, new_seq2

In [ ]:
seq1 = [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
seq2 = [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0]

new_seq1, new_seq2 = uniform_crossover(seq1, seq2, 0.5)

print(seq2str(seq1))
print(seq2str(seq2))
print('\n')
print(seq2str(new_seq1))
print(seq2str(new_seq2))

000001000000000
010100101010000


010101000010000
000000101000000


#Real Numbers

uniform_mutation

In [42]:
min, max, num = -1, 1, 20
# uniform_mutation = lambda min, max, num : np.random.randint(min*10, max*10, num)/10
uniform_mutation = lambda min, max, num : np.random.uniform(min, max, num)

uniform_mutation(min, max, num)

array([-0.1340026 ,  0.66618048, -0.36707075, -0.16163296, -0.06621411,
       -0.70521906, -0.1976178 , -0.62300651, -0.24897223,  0.50180962,
        0.61550294, -0.33791723, -0.91262257,  0.20687134, -0.40490904,
        0.12914691, -0.48673126,  0.21296737, -0.41786103,  0.4287391 ])

non-uniform_mutation

In [38]:
mu, sigma = 0, 0.1 # mean and standard deviation
non_uniform_mutation = lambda mu, sigma, num : np.random.normal(mu, sigma, num)/10

non_uniform_mutation(mu, sigma, num)

array([-0.01311365, -0.01350387,  0.00524   , -0.00518761, -0.00698356,
        0.00055294,  0.00316299,  0.00699153,  0.00505169,  0.00204172,
       -0.02440528, -0.00869232,  0.01027754,  0.00369238,  0.00164408,
       -0.00102078, -0.00087356,  0.00218218,  0.00553013,  0.00808472])

In [19]:
np.random.randint(1, 1000, num)/100

array([5.06, 0.28, 0.98, 1.38, 9.19, 0.94, 1.17, 0.46, 2.94, 2.51, 0.59,
       7.08, 3.88, 4.55, 0.2 , 3.22, 8.67, 0.8 , 4.2 , 4.62])